#!/bin/bash

CURR_DIR=`pwd`
# 默认安装位置
PROJECT_INSTALL_PATH=$HOME/.local_bin
if [ ! -d $PROJECT_INSTALL_PATH ]
then
    mkdir $PROJECT_INSTALL_PATH
fi

# 防止更新程序时， 当前脚本正在运行导致更新失败
if [ -f "$PROJECT_INSTALL_PATH/update_project_manager" ]
then
    cp $PROJECT_INSTALL_PATH/update_project_manager ./update_project_manager
    rm -f $PROJECT_INSTALL_PATH/update_project_manager
    exec ./update_project_manager
fi

git clone git@github.com:rjf12138/project_manager_bin.git
if [ -d ./project_manager_bin ]
then
    cp -rf ./project_manager_bin/ $PROJECT_INSTALL_PATH/
    cd $PROJECT_INSTALL_PATH/project_manager_bin
    # 记录项目安装目录,设置可执行目录
    project_path=`pwd`
    echo $project_path > $HOME/.project_manager.ini
    result=`cat $HOME/.bashrc | grep $project_path/program`
    echo $result
    if [ -z "$result" ]
    then
        echo "$PATH"
        echo "$project_path/program"
        echo "export PATH=$PATH:$project_path/program" >> $HOME/.bashrc
    fi
    # 将更新文件进程设为可执行
    cp ./program/update_project_manager ../
    chmod u+x ../update_project_manager
    chmod u+x ./program/clean_after_update
    chmod u+x ./program/project_v
    echo "Install successed."
else
    echo "Can't download project_manager_bin."
fi

cd $CURR_DIR
echo "Clean"
if [ -d "./project_manager_bin" ]
then
    rm -rf ./project_manager_bin
    echo "Remove ./project_manager_bin"
fi

if [ -f "./update_project_manager" ]
then
    rm -f ./update_project_manager
    echo "Remove ./update_project_manager"
fi

exit 0