#!/bin/bash

if [ ! -f $HOME/.project_manager.ini ]
then
    echo "Can't find Project install path."
    exit 127
fi

path=`cat $HOME/.project_manager.ini`
cd $path
sudo git pull origin master

exit 0